"""Property-based tests for DividendCalculator.

Tests cover:
    - get_currency_symbol: currency inference from ticker country codes
    - calculate_projections: projection DataFrame shape and math invariants
    - calculate_growth_info: compound growth formula correctness
"""

import itertools
from typing import ClassVar

import pytest
from app.utils.dividend_calculator import DividendCalculator
from hypothesis import HealthCheck, given, note, settings
from hypothesis import strategies as st

from .conftest import growth_rate_strategy, positive_dividend_strategy, ticker_strategy

# ===========================================================================
# DividendCalculator – currency symbol
# ===========================================================================


@pytest.mark.property
class TestGetCurrencySymbol:
    """Property tests for ``DividendCalculator.get_currency_symbol``.

    Properties verified:
        - Output is always one of the three valid currency symbols.
        - Country code ``US`` maps exclusively to ``$``.
        - Country code ``PL`` maps exclusively to ``PLN``.
        - Country code ``EU`` maps exclusively to ``€``.
        - Unknown or missing country code defaults to ``$``.
    """

    VALID_SYMBOLS: ClassVar[set[str]] = {"$", "PLN", "€"}

    @given(ticker_strategy())
    @settings(max_examples=300, suppress_health_check=[HealthCheck.too_slow])
    def test_output_is_known_symbol(self, ticker: str) -> None:
        """Result is always one of the three known currency symbols.

        Arrange: Any ticker string generated by ``ticker_strategy``.
        Act: Call ``get_currency_symbol`` with the ticker.
        Assert: Returned symbol is one of ``$``, ``PLN``, or ``€``.

        Args:
            ticker: A ticker string generated by ``ticker_strategy``.
        """
        note(f"ticker = {ticker!r}")
        result = DividendCalculator.get_currency_symbol(ticker)
        assert result in self.VALID_SYMBOLS, f"Unexpected symbol {result!r} for ticker {ticker!r}"

    @given(st.text(alphabet=st.characters(whitelist_categories=("Lu",)), min_size=1, max_size=6))
    @settings(max_examples=100)
    def test_us_ticker_returns_dollar(self, symbol: str) -> None:
        """Any ``SYMBOL.US`` ticker returns ``$``.

        Arrange: An uppercase-letter symbol appended with ``.US`` country code.
        Act: Call ``get_currency_symbol`` with the constructed ticker.
        Assert: Returns exactly ``$``.

        Args:
            symbol: Uppercase letters only.
        """
        ticker = f"{symbol}.US"
        assert DividendCalculator.get_currency_symbol(ticker) == "$"

    @given(st.text(alphabet=st.characters(whitelist_categories=("Lu",)), min_size=1, max_size=6))
    @settings(max_examples=100)
    def test_pl_ticker_returns_pln(self, symbol: str) -> None:
        """Any ``SYMBOL.PL`` ticker returns ``PLN``.

        Arrange: An uppercase-letter symbol appended with ``.PL`` country code.
        Act: Call ``get_currency_symbol`` with the constructed ticker.
        Assert: Returns exactly ``PLN``.

        Args:
            symbol: Uppercase letters only.
        """
        ticker = f"{symbol}.PL"
        assert DividendCalculator.get_currency_symbol(ticker) == "PLN"

    @given(st.text(alphabet=st.characters(whitelist_categories=("Lu",)), min_size=1, max_size=6))
    @settings(max_examples=100)
    def test_eu_ticker_returns_euro(self, symbol: str) -> None:
        """Any ``SYMBOL.EU`` ticker returns ``€``.

        Arrange: An uppercase-letter symbol appended with ``.EU`` country code.
        Act: Call ``get_currency_symbol`` with the constructed ticker.
        Assert: Returns exactly ``€``.

        Args:
            symbol: Uppercase letters only.
        """
        ticker = f"{symbol}.EU"
        assert DividendCalculator.get_currency_symbol(ticker) == "€"

    @given(st.text(min_size=1, max_size=10).filter(lambda t: "." not in t))
    @settings(max_examples=100)
    def test_no_dot_defaults_to_dollar(self, ticker: str) -> None:
        """A ticker with no country code suffix defaults to ``$``.

        Arrange: Any string that contains no dot character.
        Act: Call ``get_currency_symbol`` with the string.
        Assert: Returns exactly ``$``.

        Args:
            ticker: Any string without a dot.
        """
        note(f"bare ticker = {ticker!r}")
        assert DividendCalculator.get_currency_symbol(ticker) == "$"


# ===========================================================================
# DividendCalculator – projection DataFrame
# ===========================================================================


@pytest.mark.property
class TestCalculateProjections:
    """Property tests for ``DividendCalculator.calculate_projections``.

    Properties verified:
        - Output always has exactly ``years`` rows.
        - Year sequence starts at the current year and increments by 1.
        - First projected value equals ``initial_dividend``.
        - All projected values are positive for positive inputs.
        - Positive growth → strictly increasing sequence.
        - Negative growth → strictly decreasing sequence.
        - Zero growth → constant sequence.
    """

    @given(
        positive_dividend_strategy(),
        growth_rate_strategy(),
        st.integers(min_value=1, max_value=50),
    )
    @settings(max_examples=200)
    def test_row_count_equals_years(self, initial: float, rate: float, years: int) -> None:
        """DataFrame returned has exactly ``years`` rows.

        Arrange: A positive dividend, any growth rate, and an integer year count.
        Act: Call ``calculate_projections`` with those values.
        Assert: The returned DataFrame has exactly ``years`` rows.

        Args:
            initial: Starting dividend amount.
            rate: Annual growth rate percentage.
            years: Projection horizon in years.
        """
        df = DividendCalculator.calculate_projections(initial, rate, years)
        assert len(df) == years

    @given(
        positive_dividend_strategy(),
        growth_rate_strategy(),
        st.integers(min_value=1, max_value=50),
    )
    @settings(max_examples=200)
    def test_required_columns_present(self, initial: float, rate: float, years: int) -> None:
        """Output DataFrame always contains 'Year' and 'Projected Dividend' columns.

        Arrange: A positive dividend, any growth rate, and an integer year count.
        Act: Call ``calculate_projections`` with those values.
        Assert: The returned DataFrame has both ``Year`` and ``Projected Dividend`` columns.

        Args:
            initial: Starting dividend amount.
            rate: Annual growth rate percentage.
            years: Projection horizon in years.
        """
        df = DividendCalculator.calculate_projections(initial, rate, years)
        assert "Year" in df.columns
        assert "Projected Dividend" in df.columns

    @given(
        positive_dividend_strategy(),
        growth_rate_strategy(),
        st.integers(min_value=1, max_value=50),
    )
    @settings(max_examples=200)
    def test_first_value_equals_initial_dividend(self, initial: float, rate: float, years: int) -> None:
        """The first projected dividend equals ``initial_dividend`` (year 0 growth = 0).

        Arrange: A positive dividend, any growth rate, and an integer year count.
        Act: Call ``calculate_projections`` and read the first row of ``Projected Dividend``.
        Assert: First value equals ``initial`` within floating-point tolerance.

        Args:
            initial: Starting dividend amount.
            rate: Annual growth rate percentage.
            years: Projection horizon in years.
        """
        df = DividendCalculator.calculate_projections(initial, rate, years)
        assert abs(df["Projected Dividend"].iloc[0] - initial) < 1e-9

    @given(
        positive_dividend_strategy(),
        st.floats(min_value=0.1, max_value=500.0, allow_nan=False, allow_infinity=False),
        st.integers(min_value=2, max_value=30),
    )
    @settings(max_examples=200)
    def test_positive_growth_monotonically_increasing(self, initial: float, rate: float, years: int) -> None:
        """With positive growth rate the dividend sequence is strictly increasing.

        Arrange: A positive dividend, a positive growth rate (0.1–500 %), and at
            least 2 years so adjacent values can be compared.
        Act: Call ``calculate_projections`` and read the ``Projected Dividend`` column.
        Assert: Each value is strictly greater than the preceding value.

        Args:
            initial: Starting dividend amount.
            rate: Positive annual growth rate percentage (0.1–500).
            years: Projection horizon in years (at least 2 to allow comparison).
        """
        df = DividendCalculator.calculate_projections(initial, rate, years)
        dividends = df["Projected Dividend"].tolist()
        for prev, curr in itertools.pairwise(dividends):
            assert curr > prev, f"Non-increasing: {prev} -> {curr} (rate={rate})"

    @given(
        positive_dividend_strategy(),
        st.floats(min_value=-99.0, max_value=-0.1, allow_nan=False, allow_infinity=False),
        st.integers(min_value=2, max_value=30),
    )
    @settings(max_examples=200)
    def test_negative_growth_monotonically_decreasing(self, initial: float, rate: float, years: int) -> None:
        """With negative growth rate the dividend sequence is strictly decreasing.

        Arrange: A positive dividend, a negative growth rate (-99 to -0.1 %), and
            at least 2 years so adjacent values can be compared.
        Act: Call ``calculate_projections`` and read the ``Projected Dividend`` column.
        Assert: Each value is strictly less than the preceding value.

        Args:
            initial: Starting dividend amount.
            rate: Negative annual growth rate percentage (-99 to -0.1).
            years: Projection horizon in years (at least 2).
        """
        df = DividendCalculator.calculate_projections(initial, rate, years)
        dividends = df["Projected Dividend"].tolist()
        for prev, curr in itertools.pairwise(dividends):
            assert curr < prev, f"Non-decreasing: {prev} -> {curr} (rate={rate})"

    @given(positive_dividend_strategy(), st.integers(min_value=1, max_value=50))
    @settings(max_examples=100)
    def test_zero_growth_constant_sequence(self, initial: float, years: int) -> None:
        """Zero growth rate produces a constant dividend across all years.

        Arrange: A positive dividend and an integer year count; growth rate fixed at 0.
        Act: Call ``calculate_projections`` with ``rate=0.0``.
        Assert: Every value in ``Projected Dividend`` equals ``initial`` within
            floating-point tolerance.

        Args:
            initial: Starting dividend amount.
            years: Projection horizon in years.
        """
        df = DividendCalculator.calculate_projections(initial, 0.0, years)
        for value in df["Projected Dividend"]:
            assert abs(value - initial) < 1e-9, f"Expected constant {initial}, got {value}"

    @given(
        positive_dividend_strategy(),
        growth_rate_strategy(),
        st.integers(min_value=1, max_value=50),
    )
    @settings(max_examples=200)
    def test_years_column_is_consecutive(self, initial: float, rate: float, years: int) -> None:
        """Year column is a consecutive sequence without gaps.

        Arrange: A positive dividend, any growth rate, and an integer year count.
        Act: Call ``calculate_projections`` and read the ``Year`` column.
        Assert: Each year value is exactly 1 greater than the preceding value.

        Args:
            initial: Starting dividend amount.
            rate: Annual growth rate percentage.
            years: Projection horizon in years.
        """
        df = DividendCalculator.calculate_projections(initial, rate, years)
        year_values = df["Year"].tolist()
        for i in range(len(year_values) - 1):
            assert year_values[i + 1] - year_values[i] == 1, (
                f"Year gap detected: {year_values[i]} → {year_values[i + 1]}"
            )


# ===========================================================================
# DividendCalculator – growth info
# ===========================================================================


@pytest.mark.property
class TestCalculateGrowthInfo:
    """Property tests for ``DividendCalculator.calculate_growth_info``.

    Properties verified:
        - ``final_dividend`` matches the compound-interest formula directly.
        - ``total_increase`` equals ``final_dividend - initial_dividend``.
        - ``total_growth_pct`` equals ``(total_increase / initial_dividend) * 100``.
        - ``years`` in result matches the ``years`` argument.
        - Positive growth produces positive ``total_growth_pct``.
        - Zero growth produces zero ``total_growth_pct``.
    """

    @given(
        positive_dividend_strategy(),
        growth_rate_strategy(),
        st.integers(min_value=1, max_value=50),
    )
    @settings(max_examples=300)
    def test_final_dividend_matches_formula(self, initial: float, rate: float, years: int) -> None:
        """``final_dividend`` satisfies the compound growth formula.

        The invariant: ``final = initial * (1 + rate/100) ^ (years - 1)``.

        Arrange: A positive dividend, any growth rate, and an integer year count.
        Act: Call ``calculate_growth_info`` and read ``final_dividend``.
        Assert: ``final_dividend`` equals ``initial * (1 + rate/100) ^ (years - 1)``
            within floating-point tolerance.

        Args:
            initial: Starting dividend amount.
            rate: Annual growth rate percentage.
            years: Projection horizon in years.
        """
        info = DividendCalculator.calculate_growth_info(initial, rate, years)
        expected = initial * (1 + rate / 100) ** (years - 1)
        note(f"expected={expected}, final_dividend={info['final_dividend']}")
        assert abs(info["final_dividend"] - expected) < 1e-6

    @given(
        positive_dividend_strategy(),
        growth_rate_strategy(),
        st.integers(min_value=1, max_value=50),
    )
    @settings(max_examples=200)
    def test_total_increase_equals_final_minus_initial(self, initial: float, rate: float, years: int) -> None:
        """``total_increase == final_dividend - initial_dividend``.

        Arrange: A positive dividend, any growth rate, and an integer year count.
        Act: Call ``calculate_growth_info`` and read ``total_increase`` and
            ``final_dividend``.
        Assert: ``total_increase`` equals ``final_dividend - initial`` within
            floating-point tolerance.

        Args:
            initial: Starting dividend amount.
            rate: Annual growth rate percentage.
            years: Projection horizon in years.
        """
        info = DividendCalculator.calculate_growth_info(initial, rate, years)
        expected_increase = info["final_dividend"] - initial
        assert abs(info["total_increase"] - expected_increase) < 1e-9

    @given(
        positive_dividend_strategy(),
        growth_rate_strategy(),
        st.integers(min_value=1, max_value=50),
    )
    @settings(max_examples=200)
    def test_growth_pct_formula(self, initial: float, rate: float, years: int) -> None:
        """``total_growth_pct == (total_increase / initial) * 100``.

        Arrange: A positive dividend, any growth rate, and an integer year count.
        Act: Call ``calculate_growth_info`` and read ``total_growth_pct`` and
            ``total_increase``.
        Assert: ``total_growth_pct`` equals ``(total_increase / initial) * 100``
            within floating-point tolerance.

        Args:
            initial: Starting dividend amount.
            rate: Annual growth rate percentage.
            years: Projection horizon in years.
        """
        info = DividendCalculator.calculate_growth_info(initial, rate, years)
        expected_pct = (info["total_increase"] / initial) * 100
        assert abs(info["total_growth_pct"] - expected_pct) < 1e-9

    @given(
        positive_dividend_strategy(),
        growth_rate_strategy(),
        st.integers(min_value=1, max_value=50),
    )
    @settings(max_examples=100)
    def test_years_key_preserved(self, initial: float, rate: float, years: int) -> None:
        """The ``years`` key in the result matches the argument.

        Arrange: A positive dividend, any growth rate, and an integer year count.
        Act: Call ``calculate_growth_info`` and read the ``years`` key.
        Assert: ``result["years"]`` equals the ``years`` argument.

        Args:
            initial: Starting dividend amount.
            rate: Annual growth rate percentage.
            years: Projection horizon in years.
        """
        info = DividendCalculator.calculate_growth_info(initial, rate, years)
        assert info["years"] == years

    @given(
        positive_dividend_strategy(),
        st.floats(min_value=0.001, max_value=500.0, allow_nan=False, allow_infinity=False),
        st.integers(min_value=2, max_value=30),
    )
    @settings(max_examples=100)
    def test_positive_rate_positive_growth_pct(self, initial: float, rate: float, years: int) -> None:
        """Positive growth rate always yields positive ``total_growth_pct``.

        Arrange: A positive dividend, a strictly positive growth rate, and at
            least 2 years.
        Act: Call ``calculate_growth_info`` and read ``total_growth_pct``.
        Assert: ``total_growth_pct`` is greater than zero.

        Args:
            initial: Starting dividend amount.
            rate: Positive annual growth rate.
            years: Projection horizon (at least 2).
        """
        info = DividendCalculator.calculate_growth_info(initial, rate, years)
        assert info["total_growth_pct"] > 0

    @given(positive_dividend_strategy(), st.integers(min_value=1, max_value=50))
    @settings(max_examples=100)
    def test_zero_rate_zero_growth_pct(self, initial: float, years: int) -> None:
        """Zero growth rate always yields zero ``total_growth_pct``.

        Arrange: A positive dividend and an integer year count; growth rate fixed at 0.
        Act: Call ``calculate_growth_info`` with ``rate=0.0`` and read
            ``total_growth_pct``.
        Assert: ``total_growth_pct`` is zero within floating-point tolerance.

        Args:
            initial: Starting dividend amount.
            years: Projection horizon in years.
        """
        info = DividendCalculator.calculate_growth_info(initial, 0.0, years)
        assert abs(info["total_growth_pct"]) < 1e-9
